### utwórz tablicę zawierającą 10 zer

In [2]:
import numpy as np
a = np.zeros(10)
print(a)
# yos

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### utwórz tablicę zawierającą 10 piątek,

In [28]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### utwórz tablicę zawierającą liczby od 10 do 50,

In [5]:
 np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

##### utwórz macierz (tablica wielowymiarowa) o wymiarach 3x3 zawierającą liczby od 0 do 8,

In [126]:
#x1 = np.arange(9).reshape((3, 3))
#x2 = np.arange(9).reshape((3, 3))
#x3 = np.arange(9).reshape((3, 3))
#x4 = np.stack((x1, x2,x3))
print(np.random.randint(9, size=(3, 3)))

[[8 2 4]
 [3 0 5]
 [8 6 5]]


### utwórz macierz jednostkową o wymiarach 3x3,

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### utwórz macierz o wymiarach 5x5 zawierającą liczby z dystrybucji normalnej (Gaussa),

In [130]:
s = np.random.normal(0, 1, (5, 1, 5)) 
print(s)

[[[-0.13330531 -1.76544711  0.20125983 -0.86846679  0.48670862]]

 [[ 0.33091679 -0.65852848 -0.68109516 -0.98575827 -1.31991971]]

 [[-1.2272983   1.31383782 -1.46403726 -0.19636596  0.45767469]]

 [[-1.06956063 -0.3149163   0.76233998  0.2582998  -1.06426882]]

 [[ 1.19965895 -0.48203234 -0.32203971 -0.81861464 -0.70644044]]]


#### utwórz macierz o wymiarach 10x10 zawierającą liczby od 0,01 do 1 z krokiem 0,01,

In [51]:
from numpy import ogrid
s =  ogrid[0.01:1.01:0.01]
print(s)

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.  ]


#### utwórz tablicę zawierającą 20 liniowo rozłożonych liczb między 0 a 1 (włącznie z 0 i 1),

In [54]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### utwórz tablicę zawierającą losowe liczby z przedziału (1, 25), następnie zamień ją na macierz o wymiarach 5 x 5 z tymi samymi liczbami:
oblicz sumę wszystkich liczb w ww. macierzy,
oblicz średnią wszystkich liczb w ww. macierzy,
oblicz standardową dewiację dla liczb w ww. macierzy,
oblicz sumę każdej kolumny ww. macierzy i zapisz ją do tablicy.

In [80]:
arrayTo25 = np.arange(1,26,1) 
matrixWithValues = np.zeros((5,5))
k = 0

for x in range(5):
    for y in range(5):
        c = arrayTo25[k]
        matrixWithValues[x][y]+= c
        k = k + 1
        
print("sum of array is " , matrixWithValues.sum())
print("average of array is " , matrixWithValues.mean())
print("Deviation of array is " ,  np.std(matrixWithValues))
print("sum of column is" , np.sum(matrixWithValues,axis=0))

sum of array is  325.0
average of array is  13.0
Deviation of array is  7.211102550927978
sum of column is [55. 60. 65. 70. 75.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


### utwórz macierz o wymiarach 5x5 zawierającą losowe liczby z przedziału (0, 100) i:
oblicz medianę tych liczb,
znajdź najmniejszą liczbę tej macierzy,
znajdź największą liczbę tej macierzy.

In [89]:
randomMatrix = np.random.random((5,5)) 
print("median of random matrix is " , randomMatrix.mean()) #As you will see in the documentation for ndarray.mean, ndarray.mean and np.mean are "equivalent functions," so this is just a matter of semantics.
print("min value of random matrix is " , randomMatrix.min())
print("max value of random matrix is" , randomMatrix.max())
print(randomMatrix)

median of random matrix is  0.615707546409921
min value of random matrix is  0.04597971019058911
max value of random matrix is 0.9925735206574583
[[0.91315618 0.31116315 0.06441269 0.80952449 0.04597971]
 [0.97794326 0.98532435 0.28975813 0.25317663 0.99257352]
 [0.85977375 0.75309704 0.8109682  0.52997152 0.45672861]
 [0.62207058 0.28613635 0.47207495 0.51168822 0.6288689 ]
 [0.177885   0.89491371 0.88382198 0.91977562 0.94190212]]


### utwórz macierz o wymiarach różnych od siebie i większych od 1, zawierającą losowe liczby z przedziału (0, 100) i dokonaj jej transpozycji,

In [99]:
np.transpose(np.random.randint(100, size=(2, 3)))

array([[18, 16],
       [ 5, 51],
       [25, 15]])

### utwórz dwie macierze o odpowiednich wymiarach (doczytać), większych od 2 i dodaj je do siebie,

In [107]:
a = input()
m1 = np.random.randint(a, size=(3, 4))
m2 = np.random.randint(a, size=(3, 4))
print("before")
print(m1)
print(m2)
print("after adding")
print(m1 + m2)

4
before
[[1 0 1 2]
 [0 0 2 0]
 [1 2 3 0]]
[[0 0 0 3]
 [2 1 2 2]
 [0 1 2 1]]
after adding
[[1 0 1 5]
 [2 1 4 2]
 [1 3 5 1]]


#### utwórz dwie macierze o odpowiednich wymiarach (doczytać) różnych od siebie i większych od 2, a następnie pomnóż je przez siebie za pomocą dwóch różnych funkcji (np. ‘matmul’ i ‘multiply’),

In [116]:
a = input()
m1 = np.random.randint(a, size=(3, 4))
m2 = np.random.randint(a, size=(3, 4))

print("before")
print(m1)
print(m2)
print("after multiply with matmul")
print(np.transpose(m2))
print(np.matmul(m1,np.transpose(m2)))
print("after multiply with multiply")
print(np.multiply(m1,m2))

4
before
[[2 1 0 3]
 [3 2 3 3]
 [0 2 1 0]]
[[3 1 0 3]
 [3 2 2 3]
 [2 0 1 2]]
after multiply with matmul
[[3 3 2]
 [1 2 0]
 [0 2 1]
 [3 3 2]]
[[16 17 10]
 [20 28 15]
 [ 2  6  1]]
after multiply with multiply
[[6 1 0 9]
 [9 4 6 9]
 [0 0 1 0]]


tf.multiply(X, Y) does element-wise multiplication so that

[[1 2]    [[1 3]      [[1 6]
 [3 4]] .  [2 1]]  =   [6 4]]
wheras tf.matmul does matrix multiplication so that

[[1 0]    [[1 3]      [[1 3]
 [0 1]] .  [2 1]]  =   [2 1]]