# Pomocny kod do bramki or i and

In [1]:
# Implementacja jedno neuronowej sieci
  
from numpy import exp, array, random, dot, tanh 
  
# Klasa do utworzenia sieci 
class NeuralNetwork(): 
      
    def __init__(self,am): 
        #Używając seeda upewnij się że wygenerewoane wagi będą takie same
        random.seed(1) 
          
        # Matryca wag 3 na 1 
        self.weight_matrix = 2 * random.random((am, 1)) - 1
  
    # funkcja aktywacji
    def tanh(self, x): 
        return tanh(x) 
  
    # pochodnia funkcji tanh potrzebna do policzenia gradientów
    def tanh_derivative(self, x): 
        return 1.0 - tanh(x) ** 2
  
    # forward propagation  dalsza propagacja (czyli algorytm stosowany do nadzorowanego uczenia się)
    def forward_propagation(self, inputs): 
        return self.tanh(dot(inputs, self.weight_matrix)) 
      
    # Uczenie sieci neuronowej
    def train(self, train_inputs, train_outputs, 
                            num_train_iterations): 
                                  
        # Liczba iteracji, które chcemy wykonać dla tego zestawu danych wejściowych. 
        for iteration in range(num_train_iterations): 
            output = self.forward_propagation(train_inputs) 
  
            # Oblicz błąd w danych wyjściowych.
            error = train_outputs - output 
            #Przemnóż błąð przez dane wejściowe a następnie przez gradient wyliczonej z funkcji tanh do obliczenia dostosowania wag
            adjustment = dot(train_inputs.T, error *
                             self.tanh_derivative(output)) 
                               
            #Dostosuj matryce wag
            self.weight_matrix += adjustment

# Pomocny kod do bramki XOR,XNOR,NOT

In [2]:
import numpy as np 

#funkcja do zwrócenia sigmoid Który zwróci wartość pomiędzy 0,1 ale nigdy 0 ani 1
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#funkcja do zwrócenia pochodnej sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

#funkcja do utworzenia sieci to jest nadania wag,wag ukrytych,bias oraz do zwrócenia tablicy z wartości dla funkcji sigmoid
def initialData(arrayDimension,input,output):
    
    # customowy if dla bramki not
    if(arrayDimension == 2):
        inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,2,1
    else:
        inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 1,1,1
        
    #inicjalizacja z wykorzystaniem numpy do utworzenia losowych wag i bias "dodatkowe wejście"
    #funkcja uniform zastosowana do równomiernego rozmiszczenia w zadanym przedziale
    hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
    hidden_bias =np.random.uniform(size=(1,hiddenLayerNeurons))
    output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))
    output_bias = np.random.uniform(size=(1,outputLayerNeurons))
    
    #ilość epchsów czyli kro
    epochs = 10000
    lr = 0.1
    
    print("Inizjalizacyjne ukryte wagi: ")
    print(hidden_weights)
    print("Inizjalizacyjne ukryte biasy: ")
    print(hidden_bias)
    print("Inizjalizacyjne wyjścia wag: ")
    print(output_weights)
    print("Inizjalizacyjne wyjścia biasóws: ")
    print(output_bias)
    
    #Dla każdego kroku wykonaj 1*..2*..3*..
    for _ in range(epochs):
        
        #1*Propagacja do przodu
        hidden_layer_activation = np.dot(inputs,hidden_weights)
        hidden_layer_activation += hidden_bias
        hidden_layer_output = sigmoid(hidden_layer_activation)
        output_layer_activation = np.dot(hidden_layer_output,output_weights)
        output_layer_activation += output_bias
        predicted_output = sigmoid(output_layer_activation)
        
        #2*Propagacja wsteczną
        error = expected_output - predicted_output
        d_predicted_output = error * sigmoid_derivative(predicted_output)
        error_hidden_layer = d_predicted_output.dot(output_weights.T)
        d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

        #3* Aktualizację wag i biasów
        output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
        output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * lr
        hidden_weights += inputs.T.dot(d_hidden_layer) * lr
        hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr
    
    print("Ostateczne wartości wag: ")
    print(hidden_weights)
    print("Ostateczne wartości biasów Final hidden bias: ")
    print(hidden_bias)
    print("Ostateczne wartości wyjściowe wag: ")
    print(output_weights)
    print("Ostateczne wartości wyjściowe biasów: ")
    print(output_bias)

    return predicted_output

## Bramka OR

In [3]:
#Utwórz obiekt dla tablicy o wwymiarach 1x2
neural_network = NeuralNetwork(2) 
print ('Randomowe wagi na początku treningu') 
print (neural_network.weight_matrix) 
print ("") 

#dane wejściowe dla bramki or
train_inputs = array([[0, 0], [1, 1], [1, 0], [0, 1]]) 
#wyniki  bramki or
train_outputs = array([[0, 1, 1, 1]]).T 

#Trenuj sieć
neural_network.train(train_inputs, train_outputs, 50000) 
  
print ('Wartości wag po treningu') 
print (neural_network.weight_matrix) 
print ("") 

print ("DLA OR Test dla 1,0 {}".format(neural_network.forward_propagation(array([1, 0]))))
print ("DLA OR Test dla 0,1 {}".format(neural_network.forward_propagation(array([0, 1]))))
print ("DLA OR Test dla 1,1 {}".format(neural_network.forward_propagation(array([1, 1]))))
print ("DLA OR Test dla 0,0 {}".format(neural_network.forward_propagation(array([0, 0]))))

Randomowe wagi na początku treningu
[[-0.16595599]
 [ 0.44064899]]

Wartości wag po treningu
[[5.66959122]
 [5.66958217]]

DLA OR Test dla 1,0 [0.99997621]
DLA OR Test dla 0,1 [0.9999762]
DLA OR Test dla 1,1 [1.]
DLA OR Test dla 0,0 [0.]


# Bramka AND

In [4]:
neural_network = NeuralNetwork(2) 
print ('Randomowe wagi na początku treningu ') 
print (neural_network.weight_matrix) 
print ("") 
  
train_inputs = array([[0, 0], [0, 1], [1, 0], [1, 1]]) 
train_outputs = array([[0, 0, 0, 1]]).T 
  
neural_network.train(train_inputs, train_outputs, 50000) 
  
print ('Wartości wag po treningu') 
print (neural_network.weight_matrix) 
print ("") 

#Tutaj wartość powyżej 0,5 przybliżam do 1 a poniżej do 0
print("Tutaj wartość powyżej 0,5 przybliżam do 1 a poniżej do 0")
print ("DLA AND Test dla 1,0 {}".format(neural_network.forward_propagation(array([1, 0]))))
print ("DLA AND Test dla 0,1 {}".format(neural_network.forward_propagation(array([0, 1]))))
print ("DLA AND Test dla 0,0 {}".format(neural_network.forward_propagation(array([0, 0]))))
print ("DLA AND Test dla 1,1 {}".format(neural_network.forward_propagation(array([1, 1]))))

Randomowe wagi na początku treningu 
[[-0.16595599]
 [ 0.44064899]]

Wartości wag po treningu
[[0.33928515]
 [0.33928515]]

DLA AND Test dla 1,0 [0.32683906]
DLA AND Test dla 0,1 [0.32683906]
DLA AND Test dla 0,0 [0.]
DLA AND Test dla 1,1 [0.59058916]


# Bramka XOR

In [5]:
#Dane wejściowe i przyporządkowane dla nich wyjścia
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[0],[1],[1],[0]])
outputToDisplay = initialData(2,inputs,expected_output)
for index,var in enumerate(inputs):
    print("Dla {} predykcja wynosi {}".format(var,outputToDisplay[index]))

Inizjalizacyjne ukryte wagi: 
[[1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02]]
Inizjalizacyjne ukryte biasy: 
[[0.18626021 0.34556073]]
Inizjalizacyjne wyjścia wag: 
[[0.39676747]
 [0.53881673]]
Inizjalizacyjne wyjścia biasóws: 
[[0.41919451]]
Ostateczne wartości wag: 
[[2.5637445  5.03970289]
 [2.56777901 5.06698699]]
Ostateczne wartości biasów Final hidden bias: 
[[-3.82057755 -1.71878181]]
Ostateczne wartości wyjściowe wag: 
[[-5.68712816]
 [ 5.57635717]]
Ostateczne wartości wyjściowe biasów: 
[[-2.4985502]]
Dla [0 0] predykcja wynosi [0.14525855]
Dla [0 1] predykcja wynosi [0.83534545]
Dla [1 0] predykcja wynosi [0.83519507]
Dla [1 1] predykcja wynosi [0.19746471]


# Bramka XNOR

In [6]:
#Dane wejściowe i przyporządkowane dla nich wyjścia
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[1],[0],[0],[1]])
outputToDisplay = initialData(2,inputs,expected_output)
print("\n Odpowiedź od sieci po 10000 krokach: ")
for index,var in enumerate(inputs):
    print("Dla {} predykcja wynosi {}".format(var,outputToDisplay[index]))

Inizjalizacyjne ukryte wagi: 
[[0.6852195  0.20445225]
 [0.87811744 0.02738759]]
Inizjalizacyjne ukryte biasy: 
[[0.67046751 0.4173048 ]]
Inizjalizacyjne wyjścia wag: 
[[0.55868983]
 [0.14038694]]
Inizjalizacyjne wyjścia biasóws: 
[[0.19810149]]
Ostateczne wartości wag: 
[[5.78130969 3.61545682]
 [5.74968321 3.60932   ]]
Ostateczne wartości biasów Final hidden bias: 
[[-2.38833952 -5.52837456]]
Ostateczne wartości wyjściowe wag: 
[[-7.34372679]
 [ 7.98831643]]
Ostateczne wartości wyjściowe biasów: 
[[3.29078998]]

 Odpowiedź od sieci po 10000 krokach: 
Dla [0 0] predykcja wynosi [0.93731647]
Dla [0 1] predykcja wynosi [0.058175]
Dla [1 0] predykcja wynosi [0.05806921]
Dla [1 1] predykcja wynosi [0.93692936]


# Bramka NOT 

In [7]:
inputs = np.array([[0],[1]])
expected_output = np.array([[1],[0]])
outputToDisplay = initialData(1,inputs,expected_output)
print("\nOdpowiedź od sieci po 10000 krokach: ")
for index,var in enumerate(inputs):
    print("Dla {} predykcja wynosi {}".format(var,outputToDisplay[index]))

Inizjalizacyjne ukryte wagi: 
[[0.80074457]]
Inizjalizacyjne ukryte biasy: 
[[0.96826158]]
Inizjalizacyjne wyjścia wag: 
[[0.31342418]]
Inizjalizacyjne wyjścia biasóws: 
[[0.69232262]]
Ostateczne wartości wag: 
[[5.33115028]]
Ostateczne wartości biasów Final hidden bias: 
[[-2.62078268]]
Ostateczne wartości wyjściowe wag: 
[[-7.146818]]
Ostateczne wartości wyjściowe biasów: 
[[3.50034306]]

Odpowiedź od sieci po 10000 krokach: 
Dla [0] predykcja wynosi [0.95327527]
Dla [1] predykcja wynosi [0.03913936]
